services:
  db:
    container_name: youqueue-db
    image: postgres:18.1-alpine3.23
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - youqueue-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    container_name: youqueue-server
    build:
      context: ./server
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DB_URL: ${DB_URL}
    networks:
      - youqueue-net
    depends_on:
      db:
        condition: service_healthy

networks:
  youqueue-net:
    driver: bridge
    name: youqueue-net

volumes:
  db-data:
    driver: local
    name: youqueue_db-data
